return function()
    local CyclicBuffer = require 'lib.cyclicbuf'
    local cb = CyclicBuffer(10)
    cb:print()
    cb:addItem(1)
    cb:addItem(2)
    cb:addItem(3)
    cb:addItem(4)
    cb:print()
    cb:removeItem(4)
    cb:print()
    cb:removeItem(2)
    cb:print()
    cb:addItem(5)
    cb:addItem(6)
    cb:addItem(7)
    cb:addItem(8)
    cb:addItem(9)
    cb:addItem('A')
    cb:addItem('B')
    cb:addItem('C')
    cb:addItem('D')
    cb:print()
    cb:removeItem('A')
    cb:print()
    cb:removeItem('D')
    cb:print()
    cb:increaseSize(2)
    cb:print()
    cb:removeItem('B')
    cb:removeItem('C')
    cb:print()
    cb:increaseSize(2)
    cb:print()


end